export enum Role {

    GUEST = 'ROLE_GUEST',
    USER = 'ROLE_USER',
    HELPER = 'ROLE_HELPER',
    MODERATOR = 'ROLE_MODERATOR',
    ADMINISTRATOR = 'ROLE_ADMINISTRATOR',
    HEAD_ADMINISTRATOR = 'ROLE_HEAD_ADMINISTRATOR'
}
